const actionTypes = {
  VIEW_PATIENT_DETAILS: 'VIEW_PATIENT_DETAILS',
  LOAD_patientS_SUCCESS: 'LOAD_patientS_SUCCESS',
  CYCLE_COUNT_ARRAY: 'CYCLE_COUNT_ARRAY',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  RECEIPTS_TODAY: 'RECEIPTS_TODAY',
  SHOW_MODAL: 'SHOW_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  ELEMENTS_STATE: 'ELEMENTS_STATE',
  TOGGLE_ACTION: 'TOGGLE_ACTION',
  GET_LOCUMIST: 'GET_LOCUMIST',
  GET_SERVICES: 'GET_SERVICES',
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_POSITION_DEPMT: 'GET_POSITION_DEPMT',
  GET_DRUGS: 'GET_DRUGS',
  REMOVE_ERRORS_ONCHANGE: 'REMOVE_ERRORS_ONCHANGE',
};

export default actionTypes;
